lane :release do
  sh("(cd ../../ && yarn && node ./scripts/change-version.js -f ",number_of_commits.to_s,")")
  cocoapods
  
  get_certificates           
  get_provisioning_profile   
  get_push_certificate

  enable_automatic_code_signing
  build_app(scheme: "reactAppRelease", workspace: "reactApp.xcworkspace", include_bitcode: true)
  upload_to_app_store

  sh("(cd ../../ && sh ./scritps/upload-sourcemap.ios.sh)")
end