lane :release do
  sh ("(cd .. && yarn --force)")
  cocoapods
  
  get_certificates           
  get_provisioning_profile   
  get_push_certificate

  increment_build_number(build_number: number_of_commits)

  enable_automatic_code_signing
  build_app(scheme: "reactAppRelease", workspace: "reactApp.xcworkspace", include_bitcode: true)
  upload_to_app_store
end