lane :release do
  sh("(cd ../../ && yarn && node ./scripts/change-version.js -f ",number_of_commits.to_s,")")
  
  gradle(task: "clean assembleRelease")
  upload_to_play_store

  sh("(cd ../../ && sh ./scritps/upload-sourcemap.android.sh)")
end